########################################################## CODE-GENERATIONs

generate:

########################################################## TESTs

test:
	go test -v ./... -covermode=atomic -coverprofile=coverage.out
