version: '3.7'
services:
  # prometheus:
  #   image: prom/prometheus
  #   container_name: bookman-auth-prometheus
  #   ports:
  #     - 9090:9090
  
  redis:
    image: redis
    container_name: bookman-auth-redis
    ports:
      - 6379:6379

  bookman-auth:
    build:
      dockerfile: Dockerfile
      context: services/auth
    ports:
      - 8080:8080
    depends_on:
      - redis
    restart: on-failure
