CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  email VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  date_created TIMESTAMP DEFAULT NOW()
);