name: "Release images on Okteto"

description: "Release images on Okteto"

inputs:
  namespace:
    description: "name of the namespace"
    required: true
  okteto-token:
    description: "personal okteto token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: okteto/login@latest
      with:
        token: ${{ inputs.okteto-token }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: ${{ inputs.namespace }}

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: pr-${{ github.event.number }}
        timeout: 8m
