name: "Release images on Okteto"

description: "Release images on Okteto"

inputs:
  service:
    description: "name of the service"
    required: true
  sha:
    description: "commit SHA"
    required: true
  okteto-token:
    description: "personal okteto token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: okteto/login@latest
      with:
        token: ${{ inputs.okteto-token }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@master
      with:
        name: ${{ inputs.service }}
        timeout: 5m
        variables: "COMMIT_SHA=${{ inputs.sha }}"
        filePath: .okteto/${{ inputs.service }}-pipeline.yml
