kind: Service
metadata:
  name: bookman-auth-service
  labels:
    app: bookman-auth-service
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  clusterIP: None
  selector:
    app: redis
    role: master
