name: library-ci

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --enable-all
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test -v ./services/library/... -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v1
        with:
          files: coverage.out
  publish:
    name: docker
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/mohammadne/bookman
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v2
        with:
          file: "services/library/build/Dockerfile"
          context: ./services/library
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Build bookman-library Docker image
      #   run: |
      #     docker build -f ./services/library/build/Dockerfile -t bookman-library . --tag ghcr.io/mohammadne/bookman-library:latest
      #     docker run ghcr.io/mohammadne/bookman-library:latest
      #     docker push ghcr.io/mohammadne/bookman-library:latest
