name: release

on:
  workflow_run:
    workflows: ["build"]
    branches: [master, develop]
    types:
      - completed

env:
  namespace: bookman
  okteto-token: ${{ secrets.OKTETO_TOKEN }}

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: release
    strategy:
      matrix:
        service: [auth, user, library]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/release
        with:
          namespace: ${{ env.namespace }}
          okteto-token: ${{ env.okteto-token }}
