# name: test

# on: [push]

# jobs:
#   test:
#     name: test
#     strategy:
#       matrix:
#         service: [auth, user, library]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#       - run: cd ./services/${{ matrix.service }} && make test
#       - uses: codecov/codecov-action@v1
#         with:
#           files: coverage.out
