name: test

on: [push]

jobs:
  base:
    name: library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/test
        with:
          service: library
