name: test

on: [push]

jobs:
  test:
    name: test
    strategy:
      matrix:
        service: [auth, user, library]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          service: ${{ matrix.service }}
